name: bevicschurch
description: I Love My Church is platform created to help the church members engage and enable members to take interactive sermon.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
 
version: 1.0.7+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apple_sign_in_safety: ^0.0.6
  #assets_audio_player: ^3.0.4+1
  assets_audio_player: ^3.0.5
  cached_network_image: ^3.0.0
  cloud_firestore: ^3.5.1
  firebase_database: ^9.1.7
  firebase_app_check: ^0.0.9+1
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.3
  facebook_audience_network: ^1.0.0-nullsafety.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.6.0
  firebase_messaging: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.1
  flutter_local_notifications: ^12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.2.0
  flutter_svg: ^1.0.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.0.1
  google_sign_in: ^5.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: any
  build_runner: any
  http: ^0.13.3
  unity_ads_plugin: ^0.3.4
  image_picker: ^0.7.4
  in_app_purchase: ^3.0.4
  internet_connection_checker: ^0.0.1+2
  ios_insecure_screen_detector: ^0.0.2
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  file_picker: ^4.6.1
  permission_handler: ^10.0.0
  camera: ^0.10.0+1
  image:
  just_audio: ^0.9.12
  launch_review: ^3.0.1
  lottie: ^1.1.0
  octo_image: ^1.0.0+1
  #otp_autofill: ^1.1.0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  pin_code_fields: ^7.3.0
  scratcher: ^2.1.0
  screenshot: ^1.2.1
  share_plus: ^4.0.4
  shared_preferences: ^2.0.6
  sms_autofill: ^2.2.0
  url_launcher: ^6.0.12
  wakelock: ^0.6.1+2
  webview_flutter: ^3.0.0
  country_code_picker: ^2.0.2
  flutter_windowmanager: ^0.2.0
  encrypt:
  flutter_tex: ^4.0.3+4
  logging: ^1.0.2
  audiofileplayer: ^2.1.0
  palette_generator: ^0.3.3+2
  flash: ^2.0.3+3
  flutter_downloader: ^1.8.3
  font_awesome_flutter: ^9.2.0
  package_info: ^2.0.2
  #better_player: ^0.0.83
  youtube_player_flutter: ^8.1.0
  dio: ^4.0.6
  event_bus: ^2.0.0
  flutter_widget_from_html: ^0.8.5
  clipboard: ^0.1.3
  pull_to_refresh: ^2.0.0
  tuple: ^2.0.0
  flutter_quill: ^6.0.0
  select_dialog: ^2.0.0
  flutter_material_color_picker: ^1.1.0+2
  collection: ^1.16.0
  highlight_text: ^1.4.1
  flutter_neumorphic: ^3.2.0 
  firebase_storage: ^10.3.11
  fluttertoast: ^8.0.9
  #emoji_picker_flutter: ^1.4.0
  #emoji_choose: ^0.0.2
  gugor_emoji: ^0.0.4
  firebase_core_platform_interface: 4.5.1
  fading_edge_scrollview: ^3.0.0

  better_player:
     git:
      url: https://github.com/tintran-dev/betterplayer.git
  
dependency_overrides:
   meta: ^1.8.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
    - assets/lottie/

    - assets/video/


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  
